config/routes.rb
Rails.application.routes.draw do
  namespace :backend do resources :offices end
  namespace :backend do resources :steps end
  namespace :backend do resources :file_records end
  namespace :backend do resources :persons end
  devise_for :users
  resources :steps

  resources :people

  resources :offices

  resources :file_records do
      resources :steps
      post 'archivate'
    end

  root 'file_records#index'

end

app/models/file_record.rb
class FileRecord < ActiveRecord::Base
	has_many :steps , dependent: :destroy

	after_create :start_step

	def start_step
		steps.build.start
	end

	def archivate
		steps.build.archivate_step
	end

end

app/models/office.rb
class Office < ActiveRecord::Base
	has_many :steps , dependent: :destroy

	attr_accessor :steps

	def self.start_office
		Office.find_or_create_by(name: 'Mesa de Entrada')
	end

	def archivate_office
  		Office.find_or_create_by(name: 'Archivo')
	end
end

app/models/person.rb
class Person < ActiveRecord::Base
	has_many :steps , dependent: :destroy
end

app/models/step.rb
class Step < ActiveRecord::Base
  belongs_to :file_record
  belongs_to :person
  belongs_to :office

  def start
    self.office = Office.start_office
    save
  end

  def archivate_step
    self.office.archivate_office
    save
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/backend/file_records_controller.rb
class Backend::FileRecordsController < Backend::ApplicationController
end

app/controllers/backend/offices_controller.rb
class Backend::OfficesController < Backend::ApplicationController
end

app/controllers/backend/persons_controller.rb
class Backend::PersonsController < Backend::ApplicationController
end

app/controllers/backend/steps_controller.rb
class Backend::StepsController < Backend::ApplicationController
end

app/controllers/file_records_controller.rb
class FileRecordsController < InheritedResources::Base
 
  
  protected
    def permitted_params
      params.permit(:file_record => [:title])
    end
end

app/controllers/offices_controller.rb
class OfficesController < InheritedResources::Base
  protected
    def permitted_params
      params.permit(:office => [:name])
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :dni)
    end
end

app/controllers/steps_controller.rb
class StepsController < InheritedResources::Base

 def create
 	binding.pry
 end
  protected
    def permitted_params
      params.permit(:step => [:file_record_id, :person_id, :office_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/file_records_helper.rb
module FileRecordsHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/backend/application/_footer.html.erb
<footer>
  <p>&copy; Company 2013</p>
</footer>

app/views/backend/application/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-backend-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>
    
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-backend-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/file_records/_form.html.erb
<%= form_for(@file_record) do |f| %>
  <% if @file_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@file_record.errors.count, "error") %> prohibited this file_record from being saved:</h2>

      <ul>
      <% @file_record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/file_records/edit.html.erb
<h1>Editing file_record</h1>

<%= render 'form' %>

<%= link_to 'Show', @file_record %> |
<%= link_to 'Back', file_records_path %>

app/views/file_records/index.html.erb
<h1>Listing file_records</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @file_records.each do |file_record| %>
      <tr>
        <td><%= file_record.title %></td>
        <td><%= link_to 'Show', file_record %></td>
        <td><%= link_to 'Edit', edit_file_record_path(file_record) %></td>
        <td><%= link_to 'Destroy', file_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New File record', new_file_record_path %>

app/views/file_records/new.html.erb
<h1>New file_record</h1>

<%= render 'form' %>

<%= link_to 'Back', file_records_path %>

app/views/file_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @file_record.title %>
</p>

<p>
  <strong>Step:</strong>
  	<br>
    <% @file_record.steps.each do |step| %>
  	<tr>
        <td><%= step.office.name  if step.office%></td>
    </tr>
    <%end%>
</p>

<%= link_to 'Edit', edit_file_record_path(@file_record) %> 
<%= link_to 'Back', file_records_path %>

<strong>Cargar nuevo Step:</strong>
<br>
<%= form_for [@file_record, @file_record.steps.build] do |f| %>
<%= f.collection_select(:office_id, Office.all, :id, :name) %>
<%= f.submit %>
<% end %>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Archivo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="navbar-text pull-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

<%= yield %>

</body>
</html>

app/views/layouts/backend/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Dummy" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "backend", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>
    <div id="wrap">
      <%= render 'navigation' %>
      <%= render 'action_bar'%>

      <div class="container">
        <%= render 'messages' %>
        <%= yield %>
      </div>
    </div> <!-- /container -->
    <%= render 'footer'%>

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "backend" %>
  </body>
</html>

app/views/offices/_form.html.erb
<%= form_for(@office) do |f| %>
  <% if @office.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@office.errors.count, "error") %> prohibited this office from being saved:</h2>

      <ul>
      <% @office.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offices/edit.html.erb
<h1>Editing office</h1>

<%= render 'form' %>

<%= link_to 'Show', @office %> |
<%= link_to 'Back', offices_path %>

app/views/offices/index.html.erb
<h1>Listing offices</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @offices.each do |office| %>
      <tr>
        <td><%= office.name %></td>
        <td><%= link_to 'Show', office %></td>
        <td><%= link_to 'Edit', edit_office_path(office) %></td>
        <td><%= link_to 'Destroy', office, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Office', new_office_path %>

app/views/offices/new.html.erb
<h1>New office</h1>

<%= render 'form' %>

<%= link_to 'Back', offices_path %>

app/views/offices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @office.name %>
</p>

<%= link_to 'Edit', edit_office_path(@office) %> |
<%= link_to 'Back', offices_path %>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :dni %><br>
    <%= f.text_field :dni %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Listing people</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Dni</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.dni %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Dni:</strong>
  <%= @person.dni %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/steps/_form.html.erb
<%= form_for(@step) do |f| %>
  <% if @step.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@step.errors.count, "error") %> prohibited this step from being saved:</h2>

      <ul>
      <% @step.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :file_record_id %><br>
    <%= f.text_field :file_record_id %>
  </div>
  <div class="field">
    <%= f.label :person_id %><br>
    <%= f.text_field :person_id %>
  </div>
  <div class="field">
    <%= f.label :office_id %><br>
    <%= f.text_field :office_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/steps/edit.html.erb
<h1>Editing step</h1>

<%= render 'form' %>

<%= link_to 'Show', @step %> |
<%= link_to 'Back', steps_path %>

app/views/steps/index.html.erb
<h1>Listing steps</h1>

<table>
  <thead>
    <tr>
      <th>File record</th>
      <th>Person</th>
      <th>Office</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @steps.each do |step| %>
      <tr>
        <td><%= step.file_record %></td>
        <td><%= step.person %></td>
        <td><%= step.office %></td>
        <td><%= link_to 'Show', step %></td>
        <td><%= link_to 'Edit', edit_step_path(step) %></td>
        <td><%= link_to 'Destroy', step, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Step', new_step_path %>

app/views/steps/new.html.erb
<h1>New step</h1>

<%= render 'form' %>

<%= link_to 'Back', steps_path %>

app/views/steps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>File record:</strong>
  <%= @step.file_record %>
</p>

<p>
  <strong>Person:</strong>
  <%= @step.person %>
</p>

<p>
  <strong>Office:</strong>
  <%= @step.office %>
</p>

<%= link_to 'Edit', edit_step_path(@step) %> |
<%= link_to 'Back', steps_path %>